name: Build Windows EXE
on:
  workflow_dispatch:
    inputs:
      node_range:
        description: pkg Node major range to package against.
        type: string
        required: false
        default: node24
  push:
    tags:
      - 'exe-v*'

permissions:
  contents: write

jobs:
  build:
    name: node24-win-x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo build